Cart.MVC/Controllers/CartController.cs
using Cart.MVC.Models;
using log4net;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Cart.MVC.Controllers
{
    public class CartController : Controller
    {
        OrderController orderController = new OrderController();
        ProductController productController = new ProductController();
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: Cart
        public ActionResult Index()
        {
            IEnumerable<Product> allProducts = null;
            IEnumerable<OrderHeader> myOrders = null;
            IEnumerable<OrderDetail> orderDetails = null;
            IEnumerable<CartProducts> myCartProducts = null;
            string currentUser = string.Empty;
            orderController.InitializeController(this.Request.RequestContext);
            productController.InitializeController(this.Request.RequestContext);

            try
            {
                myOrders = orderController.GetAllOrders().Where(x => x.Status.Equals("Draft", StringComparison.CurrentCultureIgnoreCase)).ToList();
                if (myOrders.Count() > 0)
                {
                    //orderDetails = new OrderController().GetOrderDetails(myOrders.FirstOrDefault().Id);

                    orderDetails = orderController.GetOrderDetails(myOrders.FirstOrDefault().Id);
                    allProducts = productController.GetAllProducts();
                    myCartProducts = allProducts
                        .Join(orderDetails,
                        a => a.Id,
                        b => b.ProductId,
                        (a, b) => new CartProducts { ProductId = a.Id, ProductTitle = a.ProductTitle, ProductCategory = a.ProductCategory, ProductPrice = a.ProductPrice, OrderDetailId = b.Id, Quantity = b.Quantity, OrderHeaderId = b.OrderHeaderId })
                        .Where(ab => ab.ProductId == ab.ProductId).ToList();
                    //myCartProducts = GetOrderDetails(myOrders);
                    //int orderAmount = Convert.ToInt32(myCartProducts.Sum(x => x.ProductPrice * x.Quantity));
                    ViewBag.TotalAmount = myOrders.FirstOrDefault().TotalAmount;
                    ViewBag.OrderHeaderID = myOrders.FirstOrDefault().Id;
                }
            }
            catch (Exception ex)
            {
                log.Error(ex.Message);
            }
            return View(myCartProducts);
        }

        // GET: Cart/Delete/5
        public ActionResult Delete(int id)
        {
            string currentUser = string.Empty;

            try
            {
                if (Session["CurrentUser"] != null)
                {
                    currentUser = ((UserManager)Session["CurrentUser"]).EmailID;
                    Task<string> callTask = Task.Run(() => DeleteAsync(currentUser, id));
                    callTask.Wait();
                    // Get the result
                    string astr = callTask.Result;
                }
            }
            catch (Exception ex)
            {
                log.Error(ex.Message);
            }

            return RedirectToAction("Index");
            //return View();
        }

        public ActionResult CheckOut()
        {
            return View();
        }

        //public ActionResult ConfirmOrder(string shippingAddress, string paymentMode)
        [HttpPost]
        public ActionResult ConfirmOrder(string shippingAddress, string paymentMethod)
        {
            string status = string.Empty;
            string currentUser = string.Empty;
            ConfirmOrder confirmOrder = new ConfirmOrder();
            string orderStatus = string.Empty;
            try
            {
                if (Session["CurrentUser"] != null)
                {
                    currentUser = ((UserManager)Session["CurrentUser"]).EmailID;
                    confirmOrder.shippingAddress = shippingAddress;
                    confirmOrder.paymentMethod = paymentMethod;
                    confirmOrder.userId = currentUser;
                }
                var data = Newtonsoft.Json.JsonConvert.SerializeObject(confirmOrder);

                string apiUrl = ConfigurationManager.AppSettings["HCLCartServiceAPI"];
                WebClient client = new WebClient();
                client.Headers["Content-type"] = "application/json";
                client.Encoding = Encoding.UTF8;
                string json = client.UploadString(apiUrl + "Cart/ConfirmOrder", data);
                if (json == "true")
                {
                    orderStatus = "Order Placed";
                }
            }
            catch (Exception ex)
            {
                log.Error(ex.Message);
            }
            return RedirectToAction("Index", "Product");
            //return View();
        }

        public IEnumerable<CartProducts> GetOrderDetails(List<OrderDetail> cartOrders)
        {
            IEnumerable<Product> allProducts = null;
            IEnumerable<CartProducts> cartProducts = new List<CartProducts>();
            productController.InitializeController(this.Request.RequestContext);

            try
            {
                allProducts = productController.GetAllProducts();

                var test = from a in allProducts
                           join b in cartOrders
                           on a.Id equals b.ProductId
                           select new { a.ProductTitle, a.ProductCategory, a.ProductPrice, b.Quantity };

                cartProducts = allProducts
                    .Join(cartOrders,
                    a => a.Id,
                    b => b.ProductId,
                    (a, b) => new CartProducts { ProductId = a.Id, ProductTitle = a.ProductTitle, ProductCategory = a.ProductCategory, ProductPrice = a.ProductPrice, OrderDetailId = b.Id, Quantity = b.Quantity, OrderHeaderId = b.OrderHeaderId })
                    .Where(ab => ab.ProductId == ab.ProductId).ToList();
            }
            catch (Exception ex)
            {
                log.Error(ex.Message);
            }
            return cartProducts;
        }



        public async Task<string> DeleteAsync(string userId, int id)
        {
            UserEntity userEntity = new UserEntity();
            userEntity.userId = userId;
            userEntity.productId = id;

            try
            {
                var data = Newtonsoft.Json.JsonConvert.SerializeObject(userEntity);

                string apiUrl = ConfigurationManager.AppSettings["HCLCartServiceAPI"] + "Cart/DeleteProductFromCart";
                using (var client = new HttpClient())
                {
                    HttpRequestMessage request = new HttpRequestMessage
                    {
                        Content = new StringContent(data, Encoding.UTF8, "application/json"),
                        Method = HttpMethod.Delete,
                        RequestUri = new Uri(apiUrl)
                    };
                    var a = await client.SendAsync(request);
                }
            }
            catch (Exception ex)
            {
                log.Error(ex.Message);
            }
            return "true";
        }
    }
}

Cart.MVC/Controllers/OrderController.cs
using Cart.MVC.Models;
using log4net;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Cart.MVC.Controllers
{
    public class OrderController : Controller
    {
        ProductController productController = new ProductController();
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        public void InitializeController(RequestContext context)
        {
            base.Initialize(context);
        }

        // GET: Order
        public ActionResult MyOrders()
        {
            IEnumerable<OrderHeader> allOrders = null;
            IEnumerable<OrderHeader> myOrders = null;
            string currentUser = string.Empty;

            allOrders = GetAllOrders();
            if (allOrders !=null)
            {
                myOrders = allOrders.Where(x => !x.Status.Equals("Draft", StringComparison.CurrentCultureIgnoreCase)).ToList();
            }
            return View(myOrders);
        }

        public ActionResult OrderDetails(int orderHeaderId)
        {

            IEnumerable<OrderDetail> orderItems = null;
            IEnumerable<CartProducts> orderItemsDetailed = null;
            IEnumerable<Product> allProducts = null;

            try
            {
                orderItems = GetOrderDetails(orderHeaderId);
                allProducts = productController.GetAllProducts();
                if (orderItems.Count() > 0 && allProducts.Count() > 0)
                {
                    orderItemsDetailed = allProducts
                        .Join(orderItems,
                        a => a.Id,
                        b => b.ProductId,
                        (a, b) => new CartProducts { ProductId = a.Id, ProductTitle = a.ProductTitle, ProductCategory = a.ProductCategory, ProductPrice = a.ProductPrice, OrderDetailId = b.Id, Quantity = b.Quantity, OrderHeaderId = b.OrderHeaderId })
                        .Where(ab => ab.ProductId == ab.ProductId).ToList();
                }
            }
            catch(Exception ex)
            {
                log.Error(ex.Message);
            }
            return View(orderItemsDetailed);
        }

        public IEnumerable<OrderHeader> GetAllOrders()
        {
            IEnumerable<OrderHeader> allOrders = null;
            string currentUser = string.Empty;

            try
            {
                if (Session["CurrentUser"] != null)
                {
                    currentUser = ((UserManager)Session["CurrentUser"]).EmailID;

                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(ConfigurationManager.AppSettings["HCLCartServiceAPI"]);
                        var responseTask = client.GetAsync("Cart/GetUserOrders/" + currentUser);
                        responseTask.Wait();

                        var result = responseTask.Result;
                        if (result.IsSuccessStatusCode)
                        {
                            var readTask = result.Content.ReadAsAsync<IList<OrderHeader>>();
                            readTask.Wait();
                            allOrders = readTask.Result.ToList();
                            log.Info(allOrders.Count()+ " orders retrieved for user: " + currentUser);
                        }
                        else
                        {
                            allOrders = Enumerable.Empty<OrderHeader>().ToList();
                            ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                        }
                    }

                }
            }
            catch(Exception ex)
            {
                log.Error(ex.Message);
            }
            return allOrders;
        }

        public IEnumerable<OrderDetail> GetOrderDetails(int orderHeaderId)
        {
            IEnumerable<OrderDetail> orderItems = null;

            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(ConfigurationManager.AppSettings["HCLCartServiceAPI"]);
                    var responseTask = client.GetAsync("Cart/GetOrderDetails/" + orderHeaderId);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<IList<OrderDetail>>();
                        readTask.Wait();
                        orderItems = readTask.Result.ToList();
                        log.Info(orderItems.Count() + " orders items found in OrderHeaderID: " + orderHeaderId);
                    }
                    else
                    {
                        orderItems = Enumerable.Empty<OrderDetail>().ToList();
                        ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                    }
                }
            }
            catch(Exception ex)
            {
                log.Error(ex.Message);
            }
            return orderItems;
        }
    }
}

Cart.MVC/Views/Shared/_Footer.cshtml
<footer class="footer container-fluid">
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-3 align-left">
            <a href="https://www.hcltech.com/digital-analytics-services" target="_blank">
                <img src="~/Content/Images/digital-analytics-img.png" class="digit-rgtmrg">
            </a>
        </div>
        <div class="col-lg-6 col-sm-6 col-sm-6 text-center footertopmerge">
            <p>Copyright <i class="fa fa-copyright" aria-hidden="true"></i>2019 HCL Technologies Ltd. All Rights Reserved.</p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 align-right">
            @*<p>
                    <a href="https://www.hcltech.com/enterprise-productivity/empfinesse" target="_blank" data-toggle="tooltip" data-placement="bottom" title="EmpFinesse" data-original-title="EmpFinesse">
                        <img src="/Images/EF.png" class="epslogo">
                    </a>
                    A product of <a href="http://hcleps.azurewebsites.net" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Enterprise Productivity Suite" data-original-title="Enterprise Productivity Suite" class="epslink">EPS</a>
                    <a href="http://hcleps.azurewebsites.net" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Enterprise Productivity Suite" data-original-title="Enterprise Productivity Suite">
                        <img src="/Images/ep-ico.png" class="epslogo">
                    </a>
                </p>*@
        </div>
    </div>
</footer>

Cart.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HCL Shopping Cart</title>
    @*<environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

    </environment>*@

    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("~/Content/Css/Template.css")
    @Styles.Render("~/Content/Css/font-awesome.css")


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    @using (Html.BeginForm("SearchProduct", "Product", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("HCL Shopping Cart", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("My Orders", "MyOrders", "Order")</li>

                    </ul>
                    <div class="dropdown user-drop btn-group">
                        <span>
                            <span id="search">
                                Search Product <input type="text" name="SearchString">
                                <input type="submit" id="search" class="btn" value="Filter" />
                                @*<input type="submit" value="Filter" class="btn" onclick="location.href='@Url.Action("SearchProduct", "Product")'" />*@
                                @*<input type="submit" value="Proceed to checkout" onclick="location.href='@Url.Action("CheckOut", "Cart")'" class="btn btn-info btn-lg" />
                                    <a id=@Html.DisplayFor(modelItem => item.Id) href="@Url.Action("AddToCart", "Product", new {productId = @Html.DisplayFor(modelItem => item.Id)})" class="btn btn-info btn-lg">*@
                            </span>
                            <a href="@Url.Action("Index", "Cart")" class="btn btn-info btn-lg" style="margin-right: 10px">
                                <span class="glyphicon glyphicon-shopping-cart" style="color:green"></span> My Cart
                            </a>
                            <i class="fa fa-user"></i>
                            <span id="lblUser">
                                @Session["CurrentUserName"]
                            </span>
                            @*<i class="fa fa-sign-out"></i>*@

                            <a href="~/Home/Login" style="color:white"><i class="fa fa-sign-out"></i></a>
                            @*@Html.ActionLink("My Cart", "Index", "Cart")*@
                        </span>

                    </div>
                </div>
            </div>
        </nav>

        @RenderBody()
        @Html.Partial("_Footer")
        


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    }
</body>
</html>

Cart.MVC/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HCL Shopping Cart</title>
    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
   

    @Styles.Render("~/Content/bootstrapCss")
    @Styles.Render("~/Content/logincss")

    @* @Scripts.Render("~/bundles/modernizr")*@
    @Scripts.Render("~/bundles/jquery")
    @*  @Scripts.Render("~/bundles/bootstrapJs")*@

    @Scripts.Render("~/bundles/loginJs")
    @RenderSection("scripts", required: false)
    <!-- Bootstrap -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" />


    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        body {
            padding: 0;
        }

        .validation-summary-valid {
            display: none;
        }

        .validation-summary-errors {
            color: #b94a48;
            text-align: center;
            top: 9em;
            position: absolute;
            right: 0;
            left: 0;
            font-size: 16px;
            color: red;
            /*max-width: 1170px;*/
            margin: auto;
        }

            .validation-summary-errors ul {
                padding: 0;
                margin: 0;
            }

        @@media screen and (max-width: 767px) {
            .validation-summary-errors {
                top: 6em;
                font-size: 14px;
            }

            .login-box {
                margin-top: 50px;
            }
        }
    </style>

</head>
<body>
    <div class="Main">
        @RenderBody()
        <hr />
        <footer>
            <p style="text-align:center; margin-top:20px;">&copy; @DateTime.Now.Year - HCL Technologies Ltd</p>
        </footer>
    </div>

</body>
</html>